chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('messages', MessagesView.as_view(), name='messages'),
    path('send_message', SendMessageView.as_view(), name='send_new_message'),
    path('send_message/<int:receiver_id>', SendMessageView.as_view(), name='send_message'),
    path('<int:sender_id>/<int:receiver_id>', ChatView.as_view(), name='chat'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("auth/", include("django.contrib.auth.urls")),
    path('', include('home.urls')),
    path('panel/', include('panel.urls')),
    path('profpanel/', include('panel_prof.urls')),
    path('chat/', include('chat.urls')),
]


# serving static and media files for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path
from . import views

app_name = 'panel'

urlpatterns = [
    path('info', views.ProposalInfoView.as_view(), name='proposal_info'),
    path('download_file/<int:id>/<str:fileName>', views.download_file, name='download_file'),
    path('accept-request', views.ProposalAcceptRequestView.as_view(), name='proposal_accept_request'),
    path('dissertation-info', views.DissertationInfoView.as_view(), name='dissertation_info'),
    path('defa-request', views.defa_request, name='defa_request'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django_jalali.db import models as jmodels

# Create your models here.

class User(AbstractUser):
    """
        User Model For The App
        storing students and professors
    """
    jmodels.jManager()
    
    phone_number = PhoneNumberField(blank=True, verbose_name='شماره تلفن')

    is_student = models.BooleanField(default=True, verbose_name='دانشجو است')
    
    is_prof = models.BooleanField(default=False, verbose_name='استاد است')
    
    def __str__(self):
        return f'{self.email}'


class Profile(models.Model):
    """
        Profile Model For Each User
        storing detailed information about users
    """

    ARSHAD = 'arshad'
    DOCTORA = 'doctora'

    MAGHTA_CHOICES = [
        (ARSHAD, 'کارشناسی ارشد'),
        (DOCTORA, 'دکتری'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_profile")

    maghta = models.CharField(
        max_length=7,
        choices=MAGHTA_CHOICES,
        default=ARSHAD,
        verbose_name='مقطع',
        blank=True
    )

    student_number = models.CharField(blank=True, null=True, max_length=100, verbose_name='شماره دانشجویی')

    study_field = models.ForeignKey('StudyField', on_delete=models.CASCADE)


class StudyField(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان')
    sub_title = models.CharField(max_length=255, verbose_name='گرایش', blank=True, null=True)
    department = models.ForeignKey('Department', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title} - {self.sub_title}'



class Department(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.title}'

messages/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.contrib.auth import get_user_model
from panel.utils import user_directory_path

# Create your models here.

User = get_user_model()

class Message(models.Model):
    sender = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='message_sender',
    )
    receiver = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='message_receiver',
        # limit_choices_to={'is_prof': True},
    )
    content = models.TextField(blank=True, null=True, default="")
    date_sent = models.DateTimeField(auto_now_add=True)
    has_file = models.BooleanField(default=False)
    file_name = models.CharField(max_length=255, default='')
    file_extention = models.CharField(max_length=10, default='')
    is_read = models.BooleanField(default=False)
    chat_file = models.FileField(
        upload_to=user_directory_path,
        validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])],
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'پیام {self.sender} برای {self.receiver}'

messages/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q, F
from django.contrib import messages as message_framework
from django.views import View
from django.contrib.auth.decorators import login_required, user_passes_test 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from core.settings import BASE_DIR
import os
from django.contrib.auth import get_user_model
from .models import Message
from .forms import MessageForm, ChatForm

# Create your views here.

User = get_user_model()

def messages(request):
    related_messages = Message.objects.all().filter(
        Q(sender__id=request.user.id) | Q(receiver__id=request.user.id)
    ).order_by('-date_sent')

    couples_set = set()
    for m in related_messages:
        if m.sender != m.receiver:
            couple = (m.sender, m.receiver)

            couples_set.add(couple)
            
    
    couples_list = list()
    for c in couples_set:
        sender = c[0]
        receiver = c[1]
        last_message = Message.objects.all().filter(
            (Q(sender__id__in = [sender.id, receiver.id]) & Q(receiver__id__in = [sender.id, receiver.id])) 
        ).order_by('-date_sent').first()

        couples_list.append({
            'sender': sender,
            'receiver': receiver,
            'last_message': last_message,
        })


        couples_list.sort(key=lambda x: x['last_message'].date_sent, reverse=True)

    couples_list_copy = list(couples_list)
    for item in couples_list:
        if item['sender'] != item['last_message'].sender:
            couples_list_copy.remove(item)

    paginator = Paginator(couples_list_copy, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    number_of_pages = page_obj.paginator.num_pages
    number_of_pages_list = [x for x in range(1, number_of_pages + 1)]

    return render(request, 'dashboard/messages.html', {
        'page_obj': page_obj,
        'num_pages': number_of_pages_list,
    })



def chat(request, sender_id, receiver_id):
    if request.user.id not in [sender_id, receiver_id]:
        message_framework.error(request, 'به این صفحه دسترسی ندارید.')
        return HttpResponseRedirect(reverse('dashboard:chat', args=[request.user.id, sender_id]))


    participants = [sender_id, receiver_id]
    messages_obj = Message.objects.all().filter(
        Q(sender__id__in = participants) & Q(receiver__id__in = participants)
    ).exclude(
        sender__id = F('receiver__id')
    ).order_by('date_sent')

    last_message = messages_obj.last()

    if request.user != last_message.sender:
        save_messages = messages_obj.update(is_read = True)

    # check to see who is the message sender
    # and send their id to the template
    message_sender = ''
    if request.user.id == sender_id:
        message_sender = User.objects.get(id=receiver_id)
    else:
        message_sender = User.objects.get(id=sender_id)

    # get the form
    form = ChatForm()

    return render(request, 'dashboard/chat.html', {
        'messages_obj': messages_obj,
        'message_sender': message_sender,
        'form': form,
    })



def send_message(request, receiver_id=None):
    if request.method == 'POST':

        # this is when request is coming from
        # chat page => then a reciever_id is sent
        if receiver_id is not None:
            receiver = User.objects.get(id=receiver_id)
            form = ChatForm(request.POST, request.FILES)
            if form.is_valid():
                chat_obj = Message()
                chat_obj.receiver = receiver
                chat_obj.sender = request.user
                if request.FILES.get('chat_file', False):
                    name = request.FILES.get('chat_file')
                    file_name, file_extention = os.path.splitext(str(name))
                    chat_obj.chat_file = request.FILES['chat_file']
                    chat_obj.has_file = True
                    chat_obj.file_name = file_name
                    chat_obj.file_extention = file_extention
                chat_obj.content = form.cleaned_data['content']
                
                chat_obj.save()
                message_framework.success(request, 'پیام شما با موفقیت ارسال شد.')
                return HttpResponseRedirect(reverse('dashboard:chat', args=[request.user.id, receiver_id]))
            else:
                message_framework.error(request, 'مشکلی به وجود آمد. دوباره تلاش کنید.')
                return HttpResponseRedirect(reverse('dashboard:chat', args=[request.user.id, receiver_id]))
                

        # this is when request is coming from
        # new_message page
        else:
            form = MessageForm(request.POST, request.FILES)
            if form.is_valid():
                if request.user == form.cleaned_data['receiver']:
                    message_framework.warning(request, 'نمی‌توانید برای خودتان پیام ارسال کنید.')
                    return HttpResponseRedirect(reverse('dashboard:send_message'))
                
                if not form.cleaned_data['receiver']:
                    message_framework.warning(request, 'دریافت کننده پیام را انتخاب کنید.')
                    return HttpResponseRedirect(reverse('dashboard:send_message'))

                if request.FILES.get('chat_file', False):
                    message_obj = Message(chat_file=request.FILES['chat_file'])
                    message_obj.is_file = True
                    message_obj.sender = request.user
                    message_obj.receiver = form.cleaned_data['receiver']
                    if form.cleaned_data['content']:
                        message_obj.content = form.cleaned_data['content']
                else:
                    message_obj = Message()
                    message_obj.sender = request.user
                    message_obj.receiver = form.cleaned_data['receiver']
                    message_obj.content = form.cleaned_data['content']

                message_obj.save()

                message_framework.success(request, 'پیام شما با موفقیت ارسال شد.')
                return HttpResponseRedirect(reverse('dashboard:messages'))
            else:
                message_framework.error(request, 'مشکلی به وجود آمد. دوباره تلاش کنید.')
                return HttpResponseRedirect(reverse('dashboard:messages'))

    if request.method == 'GET':
        form = MessageForm()
        return render(request, 'dashboard/send_message.html', {'form': form})

templates/messages/prof-chat.html
{% extends 'layout/panel-prof.html' %}
{% load static %}
{% load jformat %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div class="container panel-container pb-5">
        <h4 class="fw-bold">پیام&nbsp;{{message_sender.first_name}}&nbsp;{{message_sender.last_name}}</h4>
        {% comment %} <h6 class="text-secondary mb-5">در این بخش می‌توانید با اساتید خود مکاتبه کنید. تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6> {% endcomment %}

        <div class="chat-wrapper bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-2 border-0">
            <div class="messages w-100">

                {% for m in messages_obj %}
                    <div class="single-message {% if user != m.sender %}sender{% else %}receiver{% endif %}">
                        <small class="fw-light pb-1">{{m.sender.first_name}}&nbsp;{{m.sender.last_name}}</small>
                        <p class="fw-bold mb-1">{{m.content}}</p>
                        {% if m.has_file %}
                            <a href="{% url 'panel:download_file' m.id 'message' %}" target="_blank" style="width: fit-content;" class="btn btn-link mb-2 m-0 p-0">{{m.file_name}}{{m.file_extention}}</a>
                        {% endif %}
                        <small class="text-muted align-self-end opacity-75">{{ m.date_sent|jformat:"%Y/%m/%d - %H:%M" }}</small>
                    </div>
                {% endfor %}

            </div>

            <form action="{% url 'chat:send_message' message_sender.id %}" method="POST" enctype="multipart/form-data" class="chat-form w-100">
                {% csrf_token %}
                <div class="mb-3">
                    <textarea name="content" class="form-control" id="chat-textarea-chatpage" rows="3" placeholder="متن پیام"></textarea>
                </div>

                <div class="mb-3">
                    <label for="id_chat_file" class="form-label">فایل ضمیمه خود را انتخاب کنید</label>
                    <input class="form-control" type="file" id="id_chat_file" name="chat_file" accept=".pdf, .doc, .docx">
                </div>

                <div class="d-flex align-items-center justify-content-center">
                    <button type="submit" class="btn btn-primary me-2">ارسال پیام</button>
                    <button id="delete-button" class="btn btn-outline-primary">حذف پیام</button>
                </div>
            </form>
        </div>
        
    </div>
{% endblock body %}

{% block scripts %}
<script>
    function updateScroll(){
        var element = document.querySelector(".messages");
        element.scrollTop = element.scrollHeight;
    }
    document.addEventListener("DOMContentLoaded", updateScroll())
    document.addEventListener("DOMContentLoaded", function(){
        var deletButton = document.getElementById("delete-button");
        var textarea = document.getElementById("chat-textarea-chatpage");
        var file = document.getElementById("id_chat_file");

        deletButton.addEventListener("click", function(e){
            e.preventDefault()
            textarea.value = "";
        })
    })
</script>
{% endblock scripts %}

templates/messages/prof-messages.html
{% extends 'layout/panel-prof.html' %}
{% load static %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div x-data="{showStudentMessages: true}" class="container panel-container">
        <h4 class="fw-bold">پیام‌ها</h4>
        <h6 class="text-secondary">در این بخش می‌توانید با دانشجویانی که به شما مربوط هستند مکاتبه کنید.</h6>
        <h6 class="text-secondary">تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6>

        <a href="{% url 'chat:send_new_message' %}" class="btn btn-outline-primary mb-2 mt-3">ارسال پیام جدید</a>

        <div class="btn-group btn-group-lg w-100 messages-tabs mt-4" role="group" aria-label="Large button group">
            <button @click="showStudentMessages=true" :class="showStudentMessages ? 'current' : ''" type="button" class="btn btn-outline-primary">دانشجویان</button>
            <button @click="showStudentMessages=false" :class="showStudentMessages ? '' : 'current'" type="button" class="btn btn-outline-primary">استادان</button>
        </div>


        {% comment %} student messages {% endcomment %}
        <div x-cloak x-show.important="showStudentMessages" class="mb-5">
            
            {% for m in messages_obj %}
                {% if m.mokhatab.is_student %}
                    <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-4 border">
                        <h6><span class="text-secondary">مخاطب: </span>{{m.mokhatab.first_name}} {{m.mokhatab.last_name}} {% if not m.last_message.is_read and user != m.sender %}<span class="badge text-bg-danger" style="translate: -5px -3px;font-size:9px;">پیام جدید</span>{% endif %}</h6>
                        <p><small class="text-secondary">مقطع: </small>{{ m.mokhatab.user_profile.first.get_maghta_display }}</p>
                        <p><small class="text-secondary">رشته: </small>{{ m.mokhatab.user_profile.first.study_field }}</p>
                        {% comment %} <p><small class="text-secondary">عنوان شما: </small>استاد راهنما</p> {% endcomment %}
                        <p class="text-truncate" style="max-width:300px;"><small class="text-secondary">{{m.last_message.content}}...</small></p>
                        <a href="{% url 'chat:chat' m.sender.id m.receiver.id %}" class="btn btn-primary">باز کردن چت</a>
                    </div>
                {% endif %}
                {% empty %}
                <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-4 border">
                    <p>پیامی ندارید.</p>
                </div>
            {% endfor %}
        </div>


        {% comment %} prof messages {% endcomment %}
        <div x-cloak x-show.important="!showStudentMessages" class="pt-5">
            {% for m in messages_obj %}
                {% if m.mokhatab.is_prof %}
                    <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-b p-4 rounded-4 border">
                        <h6><span class="text-secondary">مخاطب: </span>{{m.mokhatab.first_name}} {{m.mokhatab.last_name}} {% if not m.last_message.is_read and user != m.sender %}<span class="badge text-bg-danger" style="translate: -5px -3px;font-size:9px;">پیام جدید</span>{% endif %}</h6>
                        <a href="{% url 'chat:chat' m.sender.id m.receiver.id %}" class="btn btn-primary">باز کردن چت</a>
                    </div>
                {% endif %}
            {% endfor %}

            {% if prof_count == 0 %}
                <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-b p-4 rounded-4 border">
                    <p class="m-0">پیامی ندارید.</p>
                </div>
            {% endif %}
        </div>

    </div>
{% endblock body %}

{% block script %}
{% endblock script %}

templates/messages/prof-send-messages.html
{% extends 'layout/panel-prof.html' %}
{% load static %}
{% load jformat %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div class="container panel-container pb-5">
        <h4 class="fw-bold">ارسال پیام جدید</h4>
        {% comment %} <h6 class="text-secondary mb-5">در این بخش می‌توانید با اساتید خود مکاتبه کنید. تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6> {% endcomment %}

        <div class="chat-wrapper bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-2 border-0" style="height: 333px!important;">
            <form action="" method="POST" enctype="multipart/form-data" class="chat-form w-100">
                {% csrf_token %}

                <select name="{{ form.receiver.name }}" id="{{ form.receiver.id_for_label }}" class="form-select mb-3">
                    {% for option in form.receiver %}
                        {{ option }}
                    {% endfor %}
                </select>

                <div class="mb-3">
                    <textarea name="content" class="form-control" id="chat-textarea-chatpage" rows="3" placeholder="متن پیام"></textarea>
                </div>

                <div class="mb-3">
                    <label for="id_chat_file" class="form-label">فایل ضمیمه خود را انتخاب کنید</label>
                    <input class="form-control" type="file" id="id_chat_file" name="chat_file" accept=".pdf, .doc, .docx">
                </div>                

                <div class="d-flex align-items-center justify-content-center">
                    <button type="submit" class="btn btn-primary me-2">ارسال پیام</button>
                    <button id="delete-button" class="btn btn-outline-primary">حذف پیام</button>
                </div>
            </form>
        </div>
        
    </div>
{% endblock body %}

{% block scripts %}
<script>
    function updateScroll(){
        var element = document.querySelector(".messages");
        element.scrollTop = element.scrollHeight;
    }
    document.addEventListener("DOMContentLoaded", updateScroll())
    document.addEventListener("DOMContentLoaded", function(){
        var deletButton = document.getElementById("delete-button");
        var textarea = document.getElementById("chat-textarea-chatpage");
        var file = document.getElementById("id_chat_file");

        deletButton.addEventListener("click", function(e){
            e.preventDefault()
            textarea.value = "";
        })
    })
</script>
{% endblock scripts %}

templates/messages/prof_messages.html
{% extends 'layout/panel-prof.html' %}
{% load static %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div x-data="{showStudentMessages: true}" class="container panel-container">
        <h4 class="fw-bold">پیام‌ها</h4>
        <h6 class="text-secondary">در این بخش می‌توانید با دانشجویانی که به شما مربوط هستند مکاتبه کنید.</h6>
        <h6 class="text-secondary">تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6>

        <div class="btn-group btn-group-lg w-100 messages-tabs mt-4" role="group" aria-label="Large button group">
            <button @click="showStudentMessages=true" :class="showStudentMessages ? 'current' : ''" type="button" class="btn btn-outline-primary">دانشجویان</button>
            <button @click="showStudentMessages=false" :class="showStudentMessages ? '' : 'current'" type="button" class="btn btn-outline-primary">استادان</button>
        </div>
    

        {% comment %} student messages {% endcomment %}
        <div x-cloak x-show.important="showStudentMessages" class="mb-5">
            <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-4 border">
                <h6><span class="text-secondary">مخاطب: </span>محمدمهدی شیخی</h6>
                <p><small class="text-secondary">مقطع: </small>کارشناسی ارشد</p>
                <p><small class="text-secondary">رشته: </small>روان‌شناسی عمومی</p>
                <p><small class="text-secondary">عنوان شما: </small>استاد راهنما</p>
                <button type="button" class="btn btn-primary">باز کردن چت</button>
            </div>
            
            <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-4 border">
                <h6><span class="text-secondary">مخاطب: </span>نیما سلطانی</h6>
                <p><small class="text-secondary">مقطع: </small>کارشناسی ارشد</p>
                <p><small class="text-secondary">رشته: </small>روان‌شناسی عمومی</p>
                <p><small class="text-secondary">عنوان شما: </small>استاد مشاور</p>
                <button type="button" class="btn btn-primary">باز کردن چت</button>
            </div>
        </div>


        {% comment %} prof messages {% endcomment %}
        <div x-cloak x-show.important="!showStudentMessages">
            <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-4 border">
                <h6><span class="text-secondary">مخاطب: </span>دکتر عیسی مراد</h6>
                <button type="button" class="btn btn-primary">باز کردن چت</button>
            </div>
            
            <div class="bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-4 border">
                <h6><span class="text-secondary">مخاطب: </span>دکتر حسین اسکندری</h6>
                <button type="button" class="btn btn-primary">باز کردن چت</button>
            </div>
        </div>

    </div>
{% endblock body %}

{% block script %}
{% endblock script %}

templates/messages/student-chat.html
{% extends 'layout/panel-student.html' %}
{% load static %}
{% load jformat %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div class="container panel-container pb-5">
        <h4 class="fw-bold">پیام&nbsp;{{message_sender.first_name}}&nbsp;{{message_sender.last_name}}</h4>
        {% comment %} <h6 class="text-secondary mb-5">در این بخش می‌توانید با اساتید خود مکاتبه کنید. تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6> {% endcomment %}

        <div class="chat-wrapper bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-2 border-0">
            <div class="messages w-100">

                {% for m in messages_obj %}
                    <div class="single-message {% if user != m.sender %}sender{% else %}receiver{% endif %}">
                        <small class="fw-light pb-1">{{m.sender.first_name}}&nbsp;{{m.sender.last_name}}</small>
                        <p class="fw-bold mb-1">{{m.content}}</p>
                        {% if m.has_file %}
                            <a href="{% url 'panel:download_file' m.id 'message' %}" target="_blank" style="width: fit-content;" class="btn btn-link mb-2 m-0 p-0">{{m.file_name}}{{m.file_extention}}</a>
                        {% endif %}
                        <small class="text-muted align-self-end opacity-75">{{ m.date_sent|jformat:"%Y/%m/%d - %H:%M" }}</small>
                    </div>
                {% endfor %}

            </div>

            <form action="{% url 'chat:send_message' message_sender.id %}" method="POST" enctype="multipart/form-data" class="chat-form w-100">
                {% csrf_token %}
                <div class="mb-3">
                    <textarea name="content" class="form-control" id="chat-textarea-chatpage" rows="3" placeholder="متن پیام"></textarea>
                </div>

                <div class="mb-3">
                    <label for="id_chat_file" class="form-label">فایل ضمیمه خود را انتخاب کنید</label>
                    <input class="form-control" type="file" id="id_chat_file" name="chat_file" accept=".pdf, .doc, .docx">
                </div>

                <div class="d-flex align-items-center justify-content-center">
                    <button type="submit" class="btn btn-primary me-2">ارسال پیام</button>
                    <button id="delete-button" class="btn btn-outline-primary">حذف پیام</button>
                </div>
            </form>
        </div>
        
    </div>
{% endblock body %}

{% block scripts %}
<script>
    function updateScroll(){
        var element = document.querySelector(".messages");
        element.scrollTop = element.scrollHeight;
    }
    document.addEventListener("DOMContentLoaded", updateScroll())
    document.addEventListener("DOMContentLoaded", function(){
        var deletButton = document.getElementById("delete-button");
        var textarea = document.getElementById("chat-textarea-chatpage");
        var file = document.getElementById("id_chat_file");

        deletButton.addEventListener("click", function(e){
            e.preventDefault()
            textarea.value = "";
        })
    })
</script>
{% endblock scripts %}

templates/messages/student-messages.html
{% extends 'layout/panel-student.html' %}
{% load static %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div class="container panel-container pb-5">
        <h4 class="fw-bold">پیام‌ها</h4>
        <h6 class="text-secondary">در این بخش می‌توانید با اساتید خود مکاتبه کنید. تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6>
        
        <a href="{% url 'chat:send_new_message' %}" class="btn btn-outline-primary mb-4 mt-3">ارسال پیام جدید</a>

        {% for m in messages_obj %}
            <div class="bg-white shadow d-flex flex-column align-items-start mb-4 p-4 rounded-4 border">
                <h6><span class="text-secondary">مخاطب: </span>دکتر {{m.mokhatab.first_name}} {{m.mokhatab.last_name}} {% if not m.last_message.is_read and user != m.sender %}<span class="badge text-bg-danger" style="translate: -5px -3px;font-size:9px;">پیام جدید</span>{% endif %}</h6>
                <p class="text-truncate" style="max-width:300px;"><small class="text-secondary">{{m.last_message.content}}...</small></p>
                <a href="{% url 'chat:chat' m.sender.id m.receiver.id %}" class="btn btn-primary">باز کردن چت</a>
            </div>
        {% endfor %}
        
    </div>
{% endblock body %}

{% block script %}
{% endblock script %}

templates/messages/student-send-messages.html
{% extends 'layout/panel-student.html' %}
{% load static %}
{% load jformat %}

{% block styles %}{% endblock styles %}

{% block body %}
    <div class="container panel-container pb-5">
        <h4 class="fw-bold">ارسال پیام جدید</h4>
        {% comment %} <h6 class="text-secondary mb-5">در این بخش می‌توانید با اساتید خود مکاتبه کنید. تمام چک‌ کردن‌های فایل‌های خود را اینجا انجام دهید.</h6> {% endcomment %}

        <div class="chat-wrapper bg-white shadow d-flex flex-column align-items-start mb-3 mt-5 p-4 rounded-2 border-0" style="height: 333px!important;">
            <form action="" method="POST" enctype="multipart/form-data" class="chat-form w-100">
                {% csrf_token %}

                <select name="{{ form.receiver.name }}" id="{{ form.receiver.id_for_label }}" class="form-select mb-3">
                    {% for option in form.receiver %}
                        {{ option }}
                    {% endfor %}
                </select>

                <div class="mb-3">
                    <textarea name="content" class="form-control" id="chat-textarea-chatpage" rows="3" placeholder="متن پیام"></textarea>
                </div>

                <div class="mb-3">
                    <label for="id_chat_file" class="form-label">فایل ضمیمه خود را انتخاب کنید</label>
                    <input class="form-control" type="file" id="id_chat_file" name="chat_file" accept=".pdf, .doc, .docx">
                </div>                

                <div class="d-flex align-items-center justify-content-center">
                    <button type="submit" class="btn btn-primary me-2">ارسال پیام</button>
                    <button id="delete-button" class="btn btn-outline-primary">حذف پیام</button>
                </div>
            </form>
        </div>
        
    </div>
{% endblock body %}

{% block scripts %}
<script>
    function updateScroll(){
        var element = document.querySelector(".messages");
        element.scrollTop = element.scrollHeight;
    }
    document.addEventListener("DOMContentLoaded", updateScroll())
    document.addEventListener("DOMContentLoaded", function(){
        var deletButton = document.getElementById("delete-button");
        var textarea = document.getElementById("chat-textarea-chatpage");
        var file = document.getElementById("id_chat_file");

        deletButton.addEventListener("click", function(e){
            e.preventDefault()
            textarea.value = "";
        })
    })
</script>
{% endblock scripts %}