chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('messages', MessagesView.as_view(), name='messages'),
    path('send_message', SendMessageView.as_view(), name='send_new_message'),
    path('send_message/<int:receiver_id>', SendMessageView.as_view(), name='send_message'),
    path('<int:sender_id>/<int:receiver_id>', ChatView.as_view(), name='chat'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("auth/", include("django.contrib.auth.urls")),
    path('', include('home.urls')),
    path('panel/', include('panel.urls')),
    path('profpanel/', include('panel_prof.urls')),
    path('chat/', include('chat.urls')),
]


# serving static and media files for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

panel_prof/urls.py
from django.urls import path
from . import views

app_name = 'panel_prof'

urlpatterns = [
    path('info', views.ProposalInfoProfView.as_view(), name='proposal_info'),
    path('proposal-accept', views.ProposalAcceptView.as_view(), name='proposal_accept'),
    path('accept-request', views.AcceptRequest.as_view(), name='accept_request'),
    path('proposal-assessment', views.proposal_assessment, name='proposal_assessment'),
    path('dissertation-judgment', views.dissertation_judgment, name='dissertation_judgment'),
]

home/models.py
from django.db import models

# Create your models here.

panel_prof/models.py
from django.db import models

# Create your models here.

panel_prof/forms.py
from django import forms
from panel.models import Proposal
from django.contrib.auth import get_user_model


User = get_user_model()

class MyModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.first_name} {obj.last_name}"


class ProposalActionForm(forms.Form):
    proposal_id = forms.IntegerField()
    action = forms.ChoiceField(choices=[('accept-rahnama', 'Accept Rahnama'), ('accept-moshaver', 'Accept Moshaver'), ('reject', 'Reject')])

    def clean(self):
        cleaned_data = super().clean()
        proposal_id = cleaned_data.get('proposal_id')
        action = cleaned_data.get('action')

        if not Proposal.objects.filter(pk=proposal_id).exists():
            raise forms.ValidationError("Invalid proposal ID.")

        return cleaned_data


class ProposalAdminForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ['profs_arzyab']

    profs = User.objects.filter(is_prof=True)

    p_id = forms.IntegerField()

    profs_arzyab = MyModelMultipleChoiceField(
        queryset=profs,
        to_field_name= 'id',
    )

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

panel_prof/views.py
from django.shortcuts import render
from django.views import View
from django.db.models import Q, F
from panel.models import Proposal
from .forms import ProposalActionForm, ProposalAdminForm
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages as message_framework

# Professor panel views

class ProposalInfoProfView(View):
    template_name = 'panel-prof/proposal-info.html'
    
    def get(self, request, *args, **kwargs):
        # Get proposals where the professor is either prof_rahnama or prof_moshaver
        rahnama_proposals = Proposal.objects.filter(
            Q(prof_rahnama=request.user)
        )

        moshaver_proposals = Proposal.objects.filter(
            Q(prof_moshaver=request.user)
        )
        
        context = {
            'rahnama_proposals': rahnama_proposals,
            'moshaver_proposals': moshaver_proposals,
        }
        return render(request, self.template_name, context)



class ProposalAcceptView(View):
    template_name = 'panel-prof/proposal-accept.html'

    def post(self, request, *args, **kwargs):
        form = ProposalActionForm(request.POST)
        
        if form.is_valid():
            proposal_id = form.cleaned_data['proposal_id']
            action = form.cleaned_data['action']
            proposal = Proposal.objects.get(pk=proposal_id)

            if action == "accept-rahnama":
                proposal.status = Proposal.WF_MOSHAVER_CONFIRM
                proposal.rahnama_one_accepted = True
                proposal.save()
                message_framework.success(request, 'ProposalAccepted rahnama')
            
            elif action == "accept-moshaver":
                proposal.status = Proposal.WF_ARZYAB_ASIGNMENT
                proposal.moshaver_one_accepted = True
                proposal.save()
                message_framework.success(request, 'ProposalAccepted moshaver')

            elif action == "reject":
                # Redirect to chat page
                message_framework.warning(request, 'ProposalRejected')
                return HttpResponseRedirect(reverse('chat:chat', args=[request.user.id, proposal.owner.id]))
        else:
            pass
            # Handle form errors here

        return HttpResponseRedirect(reverse('panel_prof:proposal_accept'))
    
    def get(self, request, *args, **kwargs):
        # Get proposals where the professor is either prof_rahnama or prof_moshaver
        moshaver_proposals = Proposal.objects.filter(
            Q(prof_moshaver=request.user), Q(status=Proposal.WF_MOSHAVER_CONFIRM)
        )
        rahnama_proposals = Proposal.objects.filter(
            Q(prof_rahnama=request.user), Q(status=Proposal.WF_RAHNAMA_CONFIRM)
        )


        print(moshaver_proposals)

        context = {
            'rahnama_proposals': rahnama_proposals,
            'moshaver_proposals': moshaver_proposals,
        }
        return render(request, self.template_name, context)



class AcceptRequest(View):
    template_name = 'panel-prof/accept-request.html'

    def post(self, request, *args, **kwargs):
        form = ProposalAdminForm(request.POST)
        
        if form.is_valid():
            proposal_id = form.cleaned_data['p_id']
            proposal = Proposal.objects.get(pk=proposal_id)
            
            # Update the proposal instance with the form data and save it
            form = ProposalAdminForm(request.POST, instance=proposal)
            proposal = form.save(commit=False)  # Save without committing to the database
            
            proposal.status = Proposal.WF_ARZYAB_CONFIRM
            proposal.save()  # Save the updated status
            message_framework.success(request, 'WF_ARZYAB_CONFIRM')
            return HttpResponseRedirect(reverse('panel_prof:accept_request'))
        else:
            message_framework.error(request, 'مشکل')
            return HttpResponseRedirect(reverse('panel_prof:accept_request'))

    def get(self, request, *args, **kwargs):
        # get all proposals waiting for arzyab asignment
        wf_arzyab_proposals = Proposal.objects.filter(
            Q(status=Proposal.WF_ARZYAB_ASIGNMENT)
        )

        # get all proposals waiting for final confirmation
        wf_admin_proposals = Proposal.objects.filter(
            Q(status=Proposal.WF_ADMIN_CONFIRM)
        )

        form = ProposalAdminForm()

        context = {
            'wf_arzyab_proposals': wf_arzyab_proposals,
            'wf_admin_proposals': wf_admin_proposals,
            'form': form
        }
        
        return render(request, self.template_name, context)



def proposal_assessment(request):
    return render(request, 'panel-prof/proposal-assessment.html')



def dissertation_judgment(request):
    return render(request, 'panel-prof/dissertation-judgment.html')

templates/layout/home.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>سامانه ثبت پروپوزال دانشگاه علامه طباطبایی</title>
    <meta name="theme-color" content="#3DD5F3" >
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <style>
        body {
            background-image: url('{% static 'img/banner.png' %}');
            background-repeat: no-repeat;
            background-size: cover;
            min-height: 100vh;
        }
    </style>
    {% block styles %}{% endblock styles %}
</head>
<body>
    {% comment %} navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse ps-5">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item a-wrapper mx-3">
                        <a class="nav-link active a-item" href="{% url 'panel:proposal_info' %}">ورود دانشجویان</a>
                    </li>
                    <li class="nav-item a-wrapper mx-3">
                        <a class="nav-link active a-item" href="{% url 'panel_prof:proposal_info' %}">ورود استادان</a>
                    </li>
                    <li class="nav-item a-wrapper mx-3">
                        <a class="nav-link active a-item" href="#">پشتیبانی</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item a-wrapper mx-3">
                        <a class="nav-link active a-item" href="{% url 'panel:proposal_info' %}">پروفایل من</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            
            
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas">
                <span class="navbar-toggler-icon"></span>
            </button>

        </div>
    </nav>

    {% comment %} offcanvas {% endcomment %}
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel" style="width:260px;">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasLabel"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item mb-2">
                    <a class="nav-link active" href="{% url 'panel:proposal_info' %}">ورود دانشجویان</a>
                </li>
                <li class="nav-item mb-2">
                    <a class="nav-link active" href="{% url 'panel_prof:proposal_info' %}">ورود استادان</a>
                </li>
                <li class="nav-item mb-2">
                    <a class="nav-link active" href="#">پشتیبانی</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item mb-2">
                        <a class="nav-link active" href="{% url 'panel:proposal_info' %}">پروفایل من</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

    {% block body %}{% endblock body %}

    {% comment %} footer {% endcomment %}

    <footer class="fixed-bottom bg-transparent text-center py-2 text-white">
        <div class="container">
          <small>طراحی و توسعه توسط <a href="#" style="text-decoration:none">تِک‌وایپرز</a></small>
        </div>
    </footer>

    {% block scripts %}{% endblock scripts %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/alpine.js' %}"></script>
</body>
</html>

templates/layout/panel-prof.html
{% load static %}
{% load chat_tags %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>سامانه ثبت پروپوزال دانشگاه علامه طباطبایی</title>
    <meta name="theme-color" content="#3DD5F3" >
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap-5-theme.rtl.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}" />
    {% block styles %}{% endblock styles %}
</head>
<body class="bg-light">
    {% comment %} navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-primary navbar-panel">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" style="padding-right:128px;">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item a-wrapper mx-3">
                        <a class="nav-link active a-item" href="{% url 'home:index' %}">صفحه اصلی</a>
                    </li>
                </ul>
            </div>
            
            
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-lg-none" style="translate: 0 3px;">
                <li class="nav-item a-wrapper mx-3">
                    <a class="nav-link active a-item" href="{% url 'home:index' %}">صفحه اصلی</a>
                </li>
            </ul>
        </div>
    </nav>

    {% comment %} offcanvas {% endcomment %}
    <div class="offcanvas offcanvas-start offcanvas-panel" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel" data-bs-scroll="true" data-bs-backdrop="false" >
        {% comment %} displays in lg and up without close button {% endcomment %}
        <div class="offcanvas-header pb-0">
            <h6 class="offcanvas-title" >{{ user.first_name }} {{ user.last_name }}</h6>
            <button type="button" class="btn-close d-lg-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body">
            <div class="d-grid gap-1">
                
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel_prof:proposal_info' %}current{% endif %}" href="{% url 'panel_prof:proposal_info' %}">
                    <i class="bi bi-house-fill fs-4" style="color:#3DD5F3;"></i>
                    پروپوزال‌ها
                </a>
            
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel_prof:proposal_accept' %}current{% endif %}" href="{% url 'panel_prof:proposal_accept' %}">
                    <i class="bi bi-patch-check fs-4" style="color:#B7BA00;"></i>
                    تأیید پروپروزال‌ها
                </a>
            
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel_prof:proposal_assessment' %}current{% endif %}" href="{% url 'panel_prof:proposal_assessment' %}">
                    <i class="bi bi-book-half fs-4" style="color:#FF0099;"></i>
                    پروپوزال‌های برای ارزیابی
                </a>
            
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel_prof:dissertation_judgment' %}current{% endif %}" href="{% url 'panel_prof:dissertation_judgment' %}">
                    <i class="bi bi-check-lg fs-4" style="color:#14FF9C;"></i>
                    پایان‌نامه‌های برای داوری
                </a>
                
                <a class="sidebar-item {% if request.resolver_match.view_name == 'chat:messages' %}current{% endif %}" href="{% url 'chat:messages' %}">
                    <i class="bi bi-chat-left-text fs-4" style="color:#FF77B8;"></i>
                    پیام‌ها
                    {% show_notif user %}
                </a>
                
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel_prof:accept_request' %}current{% endif %}" href="{% url 'panel_prof:accept_request' %}">
                    <i class="bi bi-check2-all fs-4" style="color:#00DF31;"></i>
                    درخواست‌های تصویب
                </a>
                
                <a class="sidebar-item" href="{% url 'logout' %}">
                    <i class="bi bi-box-arrow-right fs-4" style="color:#EB1804;"></i>
                    خروج
                </a>
            </div>
        </div>
    </div>

    {% comment %} notification toast {% endcomment %}
    <div class="toast-container position-absolute start-50 translate-middle-x" style="top:25px;">
        {% if messages %}
        <!-- Alert Box -->
        {% for message in messages %}
            <div class="toast 
            {% if message.level_tag == 'error' %}text-bg-danger{% endif %} 
            {% if message.level_tag == 'warning' %}text-bg-warning{% endif %}
            {% if message.level_tag == 'success' %}text-bg-success{% endif %}
            " role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <strong class="me-auto">
                        {% if message.level_tag == 'error' %}خطا{% endif %} 
                        {% if message.level_tag == 'warning' %}هشدار{% endif %}
                        {% if message.level_tag == 'success' %}موفقیت{% endif %}
                    </strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body {% if message.level_tag == 'error' or message.level_tag == 'success' %}text-white{% endif %}">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block body %}{% endblock body %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/myOffcanvas.js' %}"></script>
    <script src="{% static 'js/jquery-3.7.1.slim.min.js' %}"></script>
    <script src="{% static 'js/select2.full.min.js' %}"></script>
    <script src="{% static 'js/alpine.js' %}"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var toastElList = document.querySelectorAll('.toast');
            var toastList = Array.prototype.slice.call(toastElList).map(function(toastEl) {
                return new bootstrap.Toast(toastEl, { delay: 10000 });
            });
            
            toastList.forEach(function(toastEl) {
                if (toastEl) {
                    toastEl.show();
                }
            });
        });
    </script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/layout/panel-student.html
{% load static %}
{% load chat_tags %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>سامانه ثبت پروپوزال دانشگاه علامه طباطبایی</title>
    <meta name="theme-color" content="#3DD5F3" >
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.min.css' %}">
    {% block styles %}{% endblock styles %}
</head>
<body class="bg-light">
    {% comment %} navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-primary navbar-panel">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" style="padding-right:128px;">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item a-wrapper mx-3">
                        <a class="nav-link active a-item" href="{% url 'home:index' %}">صفحه اصلی</a>
                    </li>
                </ul>
            </div>
            
            
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-lg-none" style="translate: 0 3px;">
                <li class="nav-item a-wrapper mx-3">
                    <a class="nav-link active a-item" href="{% url 'home:index' %}">صفحه اصلی</a>
                </li>
            </ul>
        </div>
    </nav>

    {% comment %} offcanvas {% endcomment %}
    <div class="offcanvas offcanvas-start offcanvas-panel" tabindex="-1" id="offcanvas" data-bs-scroll="true" data-bs-backdrop="false">
        {% comment %} displays in lg and up without close button {% endcomment %}
        <div class="offcanvas-header pb-0">
            <div class="d-flex flex-column" style="translate: 0 10px">
                <h6 class="offcanvas-title" >{{ user.first_name }} {{ user.last_name }}</h6>
                <p>{{ user.user_profile.first.student_number }}</p>
            </div>
            <button type="button" class="btn-close d-lg-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body">
            <div class="d-grid gap-1">
                
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel:proposal_info' %}current{% endif %}" href="{% url 'panel:proposal_info' %}">
                    <i class="bi bi-house-fill fs-4" style="color:#3DD5F3;"></i>
                    اطلاعات پروپوزال
                </a>
            
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel:proposal_accept_request' %}current{% endif %}" href="{% url 'panel:proposal_accept_request' %}">
                    <i class="bi bi-card-text fs-4" style="color:#BA27FF;"></i>
                    درخواست تصویب پروپوزال
                </a>
            
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel:dissertation_info' %}current{% endif %}" href="{% url 'panel:dissertation_info' %}">
                    <i class="bi bi-book-half fs-4" style="color:#FF0099;"></i>
                    اطلاعات پایان‌نامه
                </a>
            
                <a class="sidebar-item {% if request.resolver_match.view_name == 'panel:defa_request' %}current{% endif %}" href="{% url 'panel:defa_request' %}">
                    <i class="bi bi-check-lg fs-4" style="color:#14FF9C;"></i>
                    درخواست دفاع
                </a>
                
                <a class="sidebar-item {% if request.resolver_match.view_name == 'chat:messages' %}current{% endif %}" href="{% url 'chat:messages' %}">
                    <i class="bi bi-chat-left-text fs-4" style="color:#FF77B8;"></i>
                    پیام‌ها
                    {% show_notif user %}
                </a>
                
                <a class="sidebar-item" href="{% url 'logout' %}">
                    <i class="bi bi-box-arrow-right fs-4" style="color:#EB1804;"></i>
                    خروج
                </a>
            </div>
        </div>
    </div>


    {% comment %} notification toast {% endcomment %}
    <div class="toast-container position-absolute start-50 translate-middle-x" style="top:25px;">
        {% if messages %}
        <!-- Alert Box -->
        {% for message in messages %}
            <div class="toast 
            {% if message.level_tag == 'error' %}text-bg-danger{% endif %} 
            {% if message.level_tag == 'warning' %}text-bg-warning{% endif %}
            {% if message.level_tag == 'success' %}text-bg-success{% endif %}
            " role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <strong class="me-auto">
                        {% if message.level_tag == 'error' %}text-bg-danger{% endif %} 
                        {% if message.level_tag == 'warning' %}text-bg-warning{% endif %}
                        {% if message.level_tag == 'success' %}text-bg-success{% endif %}
                    </strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body {% if message.level_tag == 'error' or message.level_tag == 'success' %}text-white{% endif %}">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block body %}{% endblock body %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/myOffcanvas.js' %}"></script>
    <script src="{% static 'js/alpine.js' %}"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var toastElList = document.querySelectorAll('.toast');
            var toastList = Array.prototype.slice.call(toastElList).map(function(toastEl) {
                return new bootstrap.Toast(toastEl, { delay: 10000 });
            });
            
            toastList.forEach(function(toastEl) {
                if (toastEl) {
                    toastEl.show();
                }
            });
        });
    </script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>